#!/usr/bin/ruby

# Copyright 2017 by Vincent Fourmond
# This program is free software. It is distributed under the terms of the
# GNU General Public License version 3.0 or later, found at
# https://www.gnu.org/copyleft/gpl.html
#
# There is NO WARRANTY.

# To get all the icon themes
# apt search -- -icon-theme | grep / | cut -d/ -f1 | xargs ./make-theme-image

require 'optparse'

# Look for the meanings of the names in https://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html
what = %w(go-next go-previous folder-new document-new accessories-calculator applications-science dialog-error dialog-error dialog-question)



OptionParser.new do |opts|
  opts.banner = "Usage: make-theme-image [options] packages..."

  opts.on("-w", "--what LIST", "comma-separated list of the images to show") do |v|
    what = v.split(/\s*,\s*/)
  end
  opts.on("-a", "--append LIST", "comma-separated list to append to images to show") do |v|
    what += v.split(/\s*,\s*/)
  end
end.parse!

print "Will look for the following icons: #{what.join(", ")}"

for file in ARGV
  puts "\n\nDealing with #{file}:"
  
  if file =~ /([^_]+)_.*deb/
    pkg = $1
  else
    pkg = file
    puts "Downloading package #{pkg}"
    system "dget", pkg
    file = Dir::glob("#{pkg}_*deb").sort {|a,b|
      File::mtime(a) <=> File::mtime(b)
    }.last
    puts " => using file #{file}"
  end


  # What we want ;-)...

  # A hash 'code-name' -> { res -> file }
  files = {}
  IO::popen(["dpkg-deb", "-c", file]) do |f|
    for l in f
      if l =~ /\.(.*\/(\d+)x(\d+)(?:@[^\/]+)?\/.*\/([^\/ ]+).(png|svg))/
        cn = $4
        res = $2.to_i
        files[cn] ||= {}
        files[cn][res] = $1
      end
    end
  end

  cmdline = ["montage", '-geometry', '64x64+2+2']
  extracted = true

  nb = 0
  miss = []
  for w in what
    # we pick the highest resolution
    if ! files[w]
      miss << w
      cmdline << 'magick:granite'
    else
      br = files[w].keys.sort.last
      fl = ".cache" + files[w][br]
      if ! File.readable?(fl)
        extracted = false
      end
      nb += 1
      cmdline << fl
    end
  end
  if miss.size > 0
    puts "Missing from theme: #{miss.join(", ")}"
  end

  cmdline << "#{pkg}.png"


  if ! extracted
    puts "Extracting #{file} to the .cache directory"
    system "dpkg-deb", "-x", file, ".cache"
  end

  if nb > 0
    # puts "Running: #{cmdline.join(" ")}"
    system *cmdline
  else
    puts "No icon found !"
  end
end
