#! /bin/sh

# Copyright 2014 by Vincent Fourmond
# This program is free software. It is distributed under the terms of the
# GNU General Public License version 3.0 or later, found at
# https://www.gnu.org/copyleft/gpl.html
#
# There is NO WARRANTY.

org=$(readlink -f "$1")
if \! -r "$org"; then
    echo "Could not read '$org'"
    exit 1;
fi

tgt=${org%%.odt}.trimmed.odt
dir=$(mktemp -d)
cd "$dir"
unzip "$org"
rm -rf [Tt]humbnails
mv META-INF/manifest.xml .
cat manifest.xml | grep -vi 'thumbnails/' > META-INF/manifest.xml
rm manifest.xml
zip -r "$tgt" .
cd -
rm -rf "$dir"